<a href="https://colab.research.google.com/github/geralarra/class2039_datasets/blob/main/Pivot_Tables_actividad_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [529]:
import pandas as pd
import numpy as np

In [530]:
info={'Company':['Ford','Ford','VW','BMW','Cooper','Cooper'],
'Stars':[1,2,np.nan,2,1,1],
'Weight':[2,4,2,2,3,None],
'Origin': ['China','Mexico','Mexico',None, 'China',pd.NaT],
'Length':[40,50,30,np.nan,45,None]
}

In [531]:
df=pd.DataFrame(data=info)
df.head()

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China    40.0
1    Ford    2.0     4.0  Mexico    50.0
2      VW    NaN     2.0  Mexico    30.0
3     BMW    2.0     2.0    None     NaN
4  Cooper    1.0     3.0   China    45.0

In [532]:
df.isnull().any()

Company    False
Stars       True
Weight      True
Origin      True
Length      True
dtype: bool

In [533]:
ndf=df.copy()
ndf.dropna(axis=1)

  Company
0    Ford
1    Ford
2      VW
3     BMW
4  Cooper
5  Cooper

In [534]:
sm=df.Stars.mean()

In [535]:
df['Stars'].fillna(value=sm,
                   inplace=True)
df

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China    40.0
1    Ford    2.0     4.0  Mexico    50.0
2      VW    1.4     2.0  Mexico    30.0
3     BMW    2.0     2.0    None     NaN
4  Cooper    1.0     3.0   China    45.0
5  Cooper    1.0     NaN     NaT     NaN

In [536]:
dx=df.Weight.mean()
df['Weight'].fillna(value=dx,
                   inplace=True)
df

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China    40.0
1    Ford    2.0     4.0  Mexico    50.0
2      VW    1.4     2.0  Mexico    30.0
3     BMW    2.0     2.0    None     NaN
4  Cooper    1.0     3.0   China    45.0
5  Cooper    1.0     2.6     NaT     NaN

In [537]:
ov=df.Origin.mode()[1]
ov

'Mexico'

In [538]:
df.Origin.mode()

0     China
1    Mexico
Name: Origin, dtype: object

In [539]:
df['Origin'].fillna(value=ov,inplace =True)
df

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China    40.0
1    Ford    2.0     4.0  Mexico    50.0
2      VW    1.4     2.0  Mexico    30.0
3     BMW    2.0     2.0  Mexico     NaN
4  Cooper    1.0     3.0   China    45.0
5  Cooper    1.0     2.6  Mexico     NaN

In [540]:
Le=df.Length.mean()
df['Length'].fillna(value=Le,
                   inplace=True)
df

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China   40.00
1    Ford    2.0     4.0  Mexico   50.00
2      VW    1.4     2.0  Mexico   30.00
3     BMW    2.0     2.0  Mexico   41.25
4  Cooper    1.0     3.0   China   45.00
5  Cooper    1.0     2.6  Mexico   41.25

In [541]:
df.to_csv('test.csv')

In [542]:
##What is the avergae stars of cars made in mexico?

In [543]:
pd.pivot_table(df,
         index='Origin',
          values='Stars',
          aggfunc=['sum','mean','median']
)

         sum  mean median
       Stars Stars  Stars
Origin
China    2.0   1.0    1.0
Mexico   6.4   1.6    1.7

In [544]:
my_pivot=pd.pivot_table(df,
         index=['Origin','Company'],
          values='Stars',
          aggfunc=['mean']
         # aggfunc=['sum','mean','median']
          #columns='Company'
)
my_pivot

                mean
               Stars
Origin Company
China  Cooper    1.0
       Ford      1.0
Mexico BMW       2.0
       Cooper    1.0
       Ford      2.0
       VW        1.4

In [545]:
my_pivot.columns

MultiIndex([('mean', 'Stars')],
           )

In [546]:
my_pivot.index

MultiIndex([( 'China', 'Cooper'),
            ( 'China',   'Ford'),
            ('Mexico',    'BMW'),
            ('Mexico', 'Cooper'),
            ('Mexico',   'Ford'),
            ('Mexico',     'VW')],
           names=['Origin', 'Company'])

In [547]:
#Median value of cooper cars in mexico

In [548]:
my_pivot

                mean
               Stars
Origin Company
China  Cooper    1.0
       Ford      1.0
Mexico BMW       2.0
       Cooper    1.0
       Ford      2.0
       VW        1.4

In [549]:
my_pivot.columns

MultiIndex([('mean', 'Stars')],
           )

In [550]:
my_pivot.index

MultiIndex([( 'China', 'Cooper'),
            ( 'China',   'Ford'),
            ('Mexico',    'BMW'),
            ('Mexico', 'Cooper'),
            ('Mexico',   'Ford'),
            ('Mexico',     'VW')],
           names=['Origin', 'Company'])

In [551]:
my_pivot.index

MultiIndex([( 'China', 'Cooper'),
            ( 'China',   'Ford'),
            ('Mexico',    'BMW'),
            ('Mexico', 'Cooper'),
            ('Mexico',   'Ford'),
            ('Mexico',     'VW')],
           names=['Origin', 'Company'])

In [552]:
my_pivot.loc[('Mexico','Cooper'),:]

mean  Stars    1.0
Name: (Mexico, Cooper), dtype: float64

In [553]:
my_pivot=pd.pivot_table(df,
         index='Origin',
          values='Stars',
          aggfunc=['mean'],
         # aggfunc=['sum','mean','median']
          columns='Company'
)
my_pivot

        mean
Company  BMW Cooper Ford   VW
Origin
China    NaN    1.0  1.0  NaN
Mexico   2.0    1.0  2.0  1.4

In [554]:
#Average stars and median weight of cars made in cooper cars Mexico

In [555]:
pd.pivot_table(df,
               index='Origin',
               aggfunc={'Stars':np.mean,'Weight':np.median},
               values=['Stars','Weight'],
               margins=True,
               columns='Company'
               )

        Stars                       Weight
Company   BMW Cooper Ford   VW  All    BMW Cooper Ford   VW  All
Origin
China     NaN    1.0  1.0  NaN  1.0    NaN    3.0  2.0  NaN  2.5
Mexico    2.0    1.0  2.0  1.4  1.6    2.0    2.6  4.0  2.0  2.3
All       2.0    1.0  1.5  1.4  1.4    2.0    2.8  3.0  2.0  2.3

In [556]:
x=pd.pivot_table(df,
               index='Origin',
               aggfunc={'Stars':np.mean,'Weight':np.median},
               values=['Stars','Weight'],
               margins=True,
               columns='Company'
               )

In [557]:
x.columns

MultiIndex([( 'Stars',    'BMW'),
            ( 'Stars', 'Cooper'),
            ( 'Stars',   'Ford'),
            ( 'Stars',     'VW'),
            ( 'Stars',    'All'),
            ('Weight',    'BMW'),
            ('Weight', 'Cooper'),
            ('Weight',   'Ford'),
            ('Weight',     'VW'),
            ('Weight',    'All')],
           names=[None, 'Company'])

In [558]:
x.index

Index(['China', 'Mexico', 'All'], dtype='object', name='Origin')

In [559]:
url='https://raw.githubusercontent.com/tec03/Datasets/main/datasets/multi_index.csv'

In [560]:
df=pd.read_csv(url,header=[0,1],index_col=[0,1])
df.head(2)

                      Night                                Day             \
                    Weather       Wind Max Temperature Weather       Wind
City   Date
London 01/07/19      Shower  SW 16 mph              18  Shower  SW 16 mph
       02/07/19  Heavy rain  SW 16 mph              17  Shower  SW 16 mph


                Max Temperature
City   Date
London 01/07/19              28
       02/07/19              29

In [561]:
df.index

MultiIndex([(   'London', '01/07/19'),
            (   'London', '02/07/19'),
            (   'London', '03/07/19'),
            (   'London', '04/07/19'),
            (   'Oxford', '01/07/19'),
            (   'Oxford', '02/07/19'),
            (   'Oxford', '03/07/19'),
            (   'Oxford', '04/07/19'),
            ('Cambridge', '01/07/19'),
            ('Cambridge', '02/07/19'),
            ('Cambridge', '03/07/19'),
            ('Cambridge', '04/07/19')],
           names=['City', 'Date'])

In [562]:
df.columns

MultiIndex([('Night',         'Weather'),
            ('Night',            'Wind'),
            ('Night', 'Max Temperature'),
            (  'Day',         'Weather'),
            (  'Day',            'Wind'),
            (  'Day', 'Max Temperature')],
           )

In [563]:
df.loc['London',('Day','Max Temperature')].mean()

29.25